# Generated by Django 4.0.4 on 2022-06-28 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('img', models.ImageField(null=True, upload_to='uploads/services/')),
            ],
        ),
        migrations.CreateModel(
            name='Temple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nameTel', models.CharField(blank=True, max_length=100, null=True)),
                ('registered_on', models.DateField(auto_now_add=True)),
                ('dist', models.CharField(max_length=50)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('main_deity', models.CharField(default='saraswathi', max_length=50)),
                ('sub_deities', models.JSONField(blank=True, null=True)),
                ('fests', models.JSONField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('place', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=20)),
                ('arch_type', models.CharField(blank=True, max_length=20, null=True)),
                ('elevation', models.CharField(blank=True, max_length=15, null=True)),
                ('intro', models.TextField(blank=True, null=True)),
                ('history', models.TextField(blank=True, null=True)),
                ('cur_status', models.TextField(blank=True, null=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TempleService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField()),
                ('duration', models.PositiveIntegerField()),
                ('slots', models.JSONField(null=True)),
                ('slot_capacity', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=20)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.service')),
                ('temple_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.temple')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_index', models.IntegerField(null=True)),
                ('service_date', models.DateField(null=True)),
                ('booked_on', models.DateField(auto_now_add=True)),
                ('status', models.CharField(max_length=20)),
                ('templeservice_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.templeservice')),
            ],
        ),
    ]
