# Generated by Django 4.0.4 on 2022-07-01 21:28

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temple',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=base.models.temples_upload_to),
        ),
        migrations.AlterField(
            model_name='service',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=base.models.services_upload_to),
        ),
    ]
