# Generated by Django 4.0.2 on 2022-04-08 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TempleService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=20)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('service_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.service')),
                ('temple_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.temple')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_index', models.IntegerField(null=True)),
                ('service_date', models.DateField(null=True)),
                ('booked_on', models.DateField(auto_now_add=True)),
                ('status', models.CharField(max_length=20)),
                ('templeservice_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.templeservice')),
            ],
        ),
    ]
