# Generated by Django 4.0.4 on 2022-07-08 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_temple_img_alter_service_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temple',
            name='fests',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='temple',
            name='sub_deities',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
