# Generated by Django 4.0.4 on 2022-07-09 04:46

import base.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_temple_fests_alter_temple_sub_deities'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplePic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=base.models.gallery_upload_to)),
                ('temple_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.temple')),
            ],
        ),
    ]
