# Generated by Django 4.0.4 on 2022-07-11 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0004_templepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
